# GPU VGA block
VGA_PATH 	= vga

# Disable preinstalled suffixes
.SUFFIXES:

# Declare phony targets
.PHONY : all vga

# Building GPU VGA driver
vga :
	cd $(VGA_PATH) && $(MAKE)

# The main target
all :